name = "PyTSP"
uuid = "21ac8556-7714-4a21-a3d1-782ae53d7567"
authors = ["Changhyun Kwon <chkwon@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
